/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ClientSchema extends BaseModel {
  static $columns = ['clientUuid', 'createdAt', 'email', 'id', 'isVerified', 'name', 'password', 'updatedAt', 'username', 'verificationToken'] as const
  $columns = ClientSchema.$columns
  @column()
  declare clientUuid: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isVerified: boolean | null
  @column()
  declare name: string | null
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare verificationToken: string | null
}

export class CommissionSchema extends BaseModel {
  static $columns = ['clientUuid', 'commissionNumber', 'createdAt', 'email', 'id', 'idea', 'name', 'noReserveAgreement', 'notes', 'refSheets', 'status', 'tosAgreement', 'type', 'updatedAt'] as const
  $columns = CommissionSchema.$columns
  @column()
  declare clientUuid: string | null
  @column()
  declare commissionNumber: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare idea: string
  @column()
  declare name: string
  @column()
  declare noReserveAgreement: boolean
  @column()
  declare notes: string | null
  @column()
  declare refSheets: any
  @column()
  declare status: any | null
  @column()
  declare tosAgreement: boolean
  @column()
  declare type: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
