/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Session: () => import('#controllers/auth/session_controller'),
    Signup: () => import('#controllers/auth/signup_controller'),
  },
  client: {
    Clients: () => import('#controllers/client/clients_controller'),
  },
  commission: {
    Commissions: () => import('#controllers/commission/commissions_controller'),
    guest: {
      Commissions: () => import('#controllers/commission/guest/commissions_controller'),
    },
  },
  email: {
    Emails: () => import('#controllers/email/emails_controller'),
  },
  page: {
    Pages: () => import('#controllers/page/pages_controller'),
  },
  password: {
    Password: () => import('#controllers/password/password_controller'),
  },
}
