/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    Session: () => import('#controllers/auth/session_controller'),
    Signup: () => import('#controllers/auth/signup_controller'),
  },
  client: {
    Clients: () => import('#controllers/client/clients_controller'),
  },
  email: {
    Emails: () => import('#controllers/email/emails_controller'),
  },
}
